-- Insert dealerships
INSERT INTO dealerships (name, location, description, website) VALUES
('Auto Galaxy', 'Los Angeles, CA', 'Premium vehicles dealership.', 'https://www.autogalaxy.com'),
('Car Kings', 'New York, NY', 'Specializing in luxury sports cars.', 'https://www.carkings.com'),
('Electric Drive', 'San Francisco, CA', 'Exclusive electric and hybrid vehicles.', 'https://www.electricdrive.com'),
('Family Motors', 'Dallas, TX', 'Family-friendly and affordable cars.', 'https://www.familymotors.com'),
('Luxury Lane', 'Miami, FL', 'High-end luxury vehicles.', 'https://www.luxurylane.com'),
('Urban Autos', 'Seattle, WA', 'Compact and city-friendly vehicles.', 'https://www.urbanautos.com'),
('SUV World', 'Denver, CO', 'Top-rated SUVs for all terrains.', 'https://www.suvworld.com'),
('EcoCars', 'Austin, TX', 'Environmentally friendly and hybrid cars.', 'https://www.ecocars.com'),
('Prime Rides', 'Atlanta, GA', 'Premium cars with quality service.', 'https://www.primerides.com'),
('Budget Cars', 'Orlando, FL', 'Affordable cars for every budget.', 'https://www.budgetcars.com'),
('Car Masters', 'Chicago, IL', 'Wide selection of cars for all tastes.', 'https://www.carmasters.com'),
('Speedy Autos', 'Los Angeles, CA', 'Speed and style combined for car lovers.', 'https://www.speedyautos.com'),
('Family Wheels', 'Houston, TX', 'Affordable cars for families and young drivers.', 'https://www.familywheels.com'),
('Global Motors', 'Boston, MA', 'Leading dealership for world-class vehicles.', 'https://www.globalmotors.com'),
('Classic Cars', 'Detroit, MI', 'Classic cars for collectors and enthusiasts.', 'https://www.classiccars.com'),
('City Autos', 'Phoenix, AZ', 'Cars for city dwellers with great fuel economy.', 'https://www.cityautos.com'),
('All Terrain Motors', 'Salt Lake City, UT', 'All-terrain vehicles for adventurers.', 'https://www.allterrainmotors.com'),
('Electric Vehicles Inc.', 'Portland, OR', 'Exclusive electric vehicles for sustainable driving.', 'https://www.electricvehicles.com'),
('Car Hub', 'San Diego, CA', 'A one-stop shop for every kind of car.', 'https://www.carhub.com'),
('Performance Autos', 'Las Vegas, NV', 'Performance cars with exceptional features.', 'https://www.performanceautos.com');

-- Insert cars
INSERT INTO cars (make, model, year, dealership_id) VALUES
('Toyota', 'Corolla', 2022, 1),
('Honda', 'Civic', 2021, 2),
('Ford', 'Mustang', 2023, 2),
('Tesla', 'Model 3', 2023, 4),
('Chevrolet', 'Tahoe', 2022, 5),
('BMW', 'X5', 2021, 7),
('Audi', 'A4', 2022, 7),
('Mercedes-Benz', 'C-Class', 2023, 8),
('Nissan', 'Altima', 2022, 9),
('Hyundai', 'Elantra', 2021, 10),
('Toyota', 'Camry', 2022, 11),
('Ford', 'Explorer', 2021, 12),
('Chevrolet', 'Impala', 2023, 13),
('BMW', '3 Series', 2022, 14),
('Tesla', 'Model S', 2023, 15),
('Audi', 'Q7', 2022, 16),
('Mercedes-Benz', 'GLA', 2021, 17),
('Honda', 'Accord', 2023, 18),
('Nissan', 'Pathfinder', 2022, 19),
('Hyundai', 'Santa Fe', 2023, 20);


INSERT INTO customers (name, email, phone, address, car_id) VALUES
('John Doe', 'john.doe@example.com', '123-456-7890', '123 Elm St, Springfield, IL', 1),
('Jane Smith', 'jane.smith@example.com', '234-567-8901', '456 Oak St, Lincoln, NE', 2),
('Alice Johnson', 'alice.johnson@example.com', '345-678-9012', '789 Maple Ave, Madison, WI', 3),
('Robert Brown', 'robert.brown@example.com', '456-789-0123', '321 Pine St, Orlando, FL', 4),
('Emily Davis', 'emily.davis@example.com', '567-890-1234', '654 Birch Rd, Denver, CO', 5),
('Michael Wilson', 'michael.wilson@example.com', '678-901-2345', '987 Cedar Dr, Boise, ID', 6),
('Jessica Taylor', 'jessica.taylor@example.com', '789-012-3456', '654 Willow Way, Salt Lake City, UT', 7),
('Daniel Thomas', 'daniel.thomas@example.com', '890-123-4567', '321 Birch Blvd, Dallas, TX', 8),
('Sophia Lee', 'sophia.lee@example.com', '901-234-5678', '987 Pine Ct, Tucson, AZ', 9),
('James Martin', 'james.martin@example.com', '123-890-4567', '654 Cedar Ave, Miami, FL', 10),
('David Evans', 'david.evans@example.com', '234-567-8901', '123 Birch St, Chicago, IL', 11),
('Rachel Adams', 'rachel.adams@example.com', '345-678-9012', '456 Oak St, Houston, TX', 12),
('Samuel Lee', 'samuel.lee@example.com', '456-789-0123', '789 Pine Rd, Phoenix, AZ', 13),
('Karen Harris', 'karen.harris@example.com', '567-890-1234', '654 Maple Blvd, Boston, MA', 14),
('Paul Jackson', 'paul.jackson@example.com', '678-901-2345', '987 Birch St, Salt Lake City, UT', 15),
('Laura White', 'laura.white@example.com', '789-012-3456', '654 Cedar Rd, Portland, OR', 16),
('Robert Lewis', 'robert.lewis@example.com', '890-123-4567', '321 Pine Ave, San Diego, CA', 17),
('Jessica Green', 'jessica.green@example.com', '901-234-5678', '987 Oak Rd, Las Vegas, NV', 18),
('George Scott', 'george.scott@example.com', '123-890-4567', '654 Willow Ave, Miami, FL', 19),
('Emily Clark', 'emily.clark@example.com', '234-567-8901', '321 Maple St, Los Angeles, CA', 20);


-- Insert customer-dealership relationships
INSERT INTO customer_dealership (customer_id, dealership_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 6),
(6, 7),
(7, 8),
(8, 9),
(9, 10),
(10, 1),
(2, 5),
(3, 6),
(4, 7),
(5, 8),
(6, 9),
(7, 10),
(8, 2),
(9, 3),
(10, 4),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(11, 14),
(12, 15),
(13, 16),
(14, 17),
(15, 18),
(16, 19),
(17, 20),
(18, 11),
(19, 12),
(20, 13);
